import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
const browser = await chromium.launch({channel:'msedge',headless:true});
const context = await browser.newContext({viewport:{width:1280,height:1000}});
const page = await context.newPage();
const errors = [];
page.on('pageerror',error => errors.push(error.message));
async function centeredPause() {
  await page.waitForFunction(() => window.spaceAttack.mode === 'paused');
  await page.locator('#title').filter({hasText:'PAUSED'}).waitFor({state:'visible'});
  assert.equal((await page.locator('#overlay').innerText()).trim(),'PAUSED');
  await page.screenshot({path:'../../work/paused.png'});
  const title = await page.locator('#title').boundingBox();
  const game = await page.locator('#game').boundingBox();
  assert.ok(Math.abs(title.x + title.width / 2 - game.x - game.width / 2) < 5);
  assert.ok(Math.abs(title.y + title.height / 2 - game.y - game.height / 2) < game.height / 4);
}
async function enterSector(key, side) {
  assert.equal(await page.evaluate(() => window.spaceAttack.awaitingEntry), true);
  await page.keyboard.down(key);
  await page.waitForFunction(() => window.spaceAttack.playerActive);
  await page.keyboard.up(key);
  const position = await page.evaluate(() => window.spaceAttack.x);
  assert.ok(side === 'left' ? position < 100 : position > 700);
}
try {
  await page.goto('http://127.0.0.1:5173');
  await page.waitForSelector('canvas');
  await page.screenshot({path:'../../work/title.png'});
  await page.getByRole('button',{name:'START GAME'}).click();
  await page.waitForFunction(() => window.spaceAttack.mode === 'playing');
  assert.equal(await page.locator('#lives .ship').count(),2);
  await page.keyboard.down('KeyA'); await page.waitForTimeout(180); await page.keyboard.up('KeyA');
  assert.ok(await page.evaluate(() => window.spaceAttack.x < 390));
  await page.keyboard.down('KeyA'); await page.keyboard.down('ArrowRight');
  const x = await page.evaluate(() => window.spaceAttack.x); await page.waitForTimeout(200);
  assert.equal(await page.evaluate(() => window.spaceAttack.x),x);
  await page.keyboard.up('KeyA'); await page.keyboard.up('ArrowRight');
  await page.keyboard.down('Space'); await page.waitForTimeout(80);
  assert.ok(await page.evaluate(() => window.spaceAttack.shot));
  await page.keyboard.up('Space');
  await page.keyboard.press('Escape');
  await centeredPause();
  const age = await page.evaluate(() => window.spaceAttack.age); await page.waitForTimeout(150);
  assert.equal(await page.evaluate(() => window.spaceAttack.age),age);
  await page.keyboard.press('Escape');
  await page.evaluate(() => {window.spaceAttack.shot = null;});
  await page.locator('canvas').click({position:{x:400,y:450}});
  assert.ok(await page.evaluate(() => window.spaceAttack.shot));
  await page.screenshot({path:'../../work/gameplay.png'});
  await page.evaluate(() => window.dispatchEvent(new Event('blur')));
  await centeredPause();
  await page.keyboard.press('Enter');
  await page.evaluate(() => {
    const w = window.spaceAttack;
    w.enemies = [Object.assign(w.enemies[0],{x:w.x,y:470,homeX:w.x,homeY:470,tier:2,points:60,dive:false,vx:0})];
    w.shot = null;
  });
  await page.keyboard.down('Space'); await page.waitForTimeout(150); await page.keyboard.up('Space');
  assert.equal(await page.evaluate(() => window.spaceAttack.score),60);
  assert.equal(await page.evaluate(() => localStorage.getItem('space-attack.high')),'60');
  assert.equal(await page.evaluate(() => window.spaceAttack.wave),2);
  assert.equal(await page.evaluate(() => window.spaceAttack.enemies.length),41);
  assert.ok(await page.evaluate(() => window.spaceAttack.respawn > 2.5));
  await page.keyboard.down('ArrowRight');
  await page.waitForTimeout(700);
  assert.equal(await page.evaluate(() => window.spaceAttack.playerActive),false);
  assert.equal(await page.evaluate(() => window.spaceAttack.entryDirection),0);
  assert.equal(await page.evaluate(() => window.spaceAttack.enemies.some(enemy => enemy.dive)),false);
  await page.keyboard.up('ArrowRight');
  await page.waitForFunction(() => window.spaceAttack.respawn <= 0);
  await enterSector('ArrowRight','left');
  for (let lives = 2; lives >= 0; lives--) {
    await page.evaluate(() => {
      const w = window.spaceAttack;
      w.diveTimer = 100;
      w.enemies.forEach(enemy => {enemy.dive = false;});
      w.bullets = [{x:w.x,y:515,vx:0}];
    });
    await page.waitForFunction(expected => window.spaceAttack.lives === expected,lives);
    const started = Date.now();
    assert.ok(await page.evaluate(() => window.spaceAttack.respawn > 2.7));
    await page.keyboard.press('Enter');
    assert.equal(await page.evaluate(() => window.spaceAttack.lives),lives);
    await page.waitForTimeout(500);
    assert.equal(await page.evaluate(() => window.spaceAttack.playerActive),false);
    assert.equal(await page.locator('#overlay').isVisible(),false);
    await page.waitForFunction(() => window.spaceAttack.respawn <= 0,{},{timeout:5000});
    assert.ok(Date.now() - started >= 2700);
    if (lives > 0) await enterSector(lives === 2 ? 'KeyA' : 'KeyD',lives === 2 ? 'right' : 'left');
  }
  assert.equal(await page.evaluate(() => window.spaceAttack.mode),'over');
  await page.getByRole('button',{name:'PLAY AGAIN'}).waitFor({state:'visible'});
  await page.screenshot({path:'../../work/game-over.png'});
  await page.keyboard.press('Enter');
  assert.equal(await page.evaluate(() => window.spaceAttack.lives),3);
  assert.equal(await page.evaluate(() => window.spaceAttack.score),0);
  assert.equal(await page.evaluate(() => window.spaceAttack.wave),1);
  await page.evaluate(() => {localStorage.clear(); sessionStorage.clear();});
  assert.ok((await context.cookies()).some(cookie => cookie.name === 'space_attack_high' && cookie.value === '60'));
  await page.reload(); await page.waitForSelector('canvas');
  assert.equal(await page.evaluate(() => window.spaceAttack.high),60);
  assert.equal(await page.evaluate(() => localStorage.getItem('space-attack.high')),'60');
  await page.setViewportSize({width:390,height:844}); await page.screenshot({path:'../../work/narrow.png'});
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth),true);
  const blocked = await browser.newContext();
  await blocked.addInitScript(() => {
    Object.defineProperty(window,'localStorage',{get() {throw new Error('Unavailable');}});
    Object.defineProperty(window,'sessionStorage',{get() {throw new Error('Unavailable');}});
    Object.defineProperty(document,'cookie',{get() {return '';},set() {}});
  });
  const fallback = await blocked.newPage();
  fallback.on('pageerror',error => errors.push(error.message));
  await fallback.goto('http://127.0.0.1:5173'); await fallback.waitForSelector('canvas');
  await fallback.getByText('STORAGE UNAVAILABLE · EXPORT TO KEEP').waitFor();
  await fallback.getByRole('button',{name:'START GAME'}).click();
  await fallback.evaluate(() => {const w = window.spaceAttack; w.kill(w.enemies[0]);});
  assert.equal(await fallback.evaluate(() => window.spaceAttack.high),60);
  const downloadPromise = fallback.waitForEvent('download');
  await fallback.locator('#settings summary').click();
  await fallback.getByRole('button',{name:'EXPORT SCORE'}).click();
  const download = await downloadPromise;
  assert.equal(download.suggestedFilename(),'space-attack-score.json');
  await fallback.locator('#score-file').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({game:'space-attack',version:1,highScore:500}))});
  await fallback.waitForFunction(() => window.spaceAttack.high === 500);
  await blocked.close();
  assert.deepEqual(errors,[]);
  console.log('Browser checks passed: movement, cancellation, shooting, centered pause, blur, immediate waves, directional entry, three-second deaths, Enter restart, cookie recovery, blocked storage export/import, narrow layout.');
} finally {
  await browser.close();
}
