import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({channel:'msedge',headless:true});
const page=await browser.newPage({viewport:{width:1280,height:1000}});
const errors=[];
page.on('pageerror',error=>errors.push(error.message));
await page.goto('http://127.0.0.1:5173');
await page.waitForSelector('canvas');
await page.screenshot({path:'../../work/title.png'});
await page.getByRole('button',{name:'START GAME'}).click();
await page.waitForFunction(()=>window.spaceAttack.mode==='playing');
assert.equal(await page.locator('#lives .ship').count(),2);
await page.keyboard.down('KeyA');await page.waitForTimeout(180);await page.keyboard.up('KeyA');
assert.ok(await page.evaluate(()=>window.spaceAttack.x<390));
await page.keyboard.down('KeyA');await page.keyboard.down('ArrowRight');
const x=await page.evaluate(()=>window.spaceAttack.x);await page.waitForTimeout(200);
assert.equal(await page.evaluate(()=>window.spaceAttack.x),x);
await page.keyboard.up('KeyA');await page.keyboard.up('ArrowRight');
await page.keyboard.down('Space');await page.waitForTimeout(80);
assert.ok(await page.evaluate(()=>window.spaceAttack.shot));
await page.keyboard.up('Space');
await page.keyboard.press('Escape');
assert.equal(await page.evaluate(()=>window.spaceAttack.mode),'paused');
const age=await page.evaluate(()=>window.spaceAttack.age);await page.waitForTimeout(150);
assert.equal(await page.evaluate(()=>window.spaceAttack.age),age);
await page.keyboard.press('Escape');
await page.evaluate(()=>{window.spaceAttack.shot=null;});
await page.locator('canvas').click({position:{x:400,y:450}});
assert.ok(await page.evaluate(()=>window.spaceAttack.shot));
await page.screenshot({path:'../../work/gameplay.png'});
await page.evaluate(()=>window.dispatchEvent(new Event('blur')));
assert.equal(await page.evaluate(()=>window.spaceAttack.mode),'paused');
await page.keyboard.press('Enter');
await page.evaluate(()=>{
  const w=window.spaceAttack;
  w.enemies=[Object.assign(w.enemies[0],{x:w.x,y:470,homeX:w.x,homeY:470,tier:2,dive:false,vx:0})];w.shot=null;
});
await page.keyboard.down('Space');await page.waitForTimeout(150);await page.keyboard.up('Space');
assert.equal(await page.evaluate(()=>window.spaceAttack.score),60);
assert.equal(await page.evaluate(()=>localStorage.getItem('space-attack.high')),'60');
await page.waitForTimeout(1850);assert.equal(await page.evaluate(()=>window.spaceAttack.wave),2);
for(let n=2;n>=0;n--){
  await page.evaluate(()=>{const w=window.spaceAttack;w.respawn=0;w.bullets=[{x:w.x,y:515,vx:0}];});
  await page.waitForTimeout(60);assert.equal(await page.evaluate(()=>window.spaceAttack.lives),n);
}
assert.equal(await page.evaluate(()=>window.spaceAttack.mode),'over');
await page.screenshot({path:'../../work/game-over.png'});
await page.getByRole('button',{name:'PLAY AGAIN'}).click();
assert.equal(await page.evaluate(()=>window.spaceAttack.lives),3);
assert.equal(await page.evaluate(()=>window.spaceAttack.score),0);
assert.equal(await page.evaluate(()=>window.spaceAttack.wave),1);
await page.reload();await page.waitForSelector('canvas');
assert.equal(await page.evaluate(()=>window.spaceAttack.high),60);
await page.setViewportSize({width:390,height:844});await page.screenshot({path:'../../work/narrow.png'});
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
assert.deepEqual(errors,[]);
console.log('Browser checks passed: start, movement, mixed-key cancellation, Space, click, pause, blur, score persistence, next wave, three deaths, game over, restart, narrow layout; no page errors.');
await browser.close();
